// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZztae4oTKf4c8hOifbYKmobenNzBRE4',
    appId: '1:792157576621:web:d8d25d701315689a3c1524',
    messagingSenderId: '792157576621',
    projectId: 'exploremate-123',
    authDomain: 'exploremate-123.firebaseapp.com',
    storageBucket: 'exploremate-123.firebasestorage.app',
    measurementId: 'G-TYMDL4FVQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGg2s3Wku79ipmlenUybNBqq3dldVPWyQ',
    appId: '1:792157576621:android:4ceb11588e96680e3c1524',
    messagingSenderId: '792157576621',
    projectId: 'exploremate-123',
    storageBucket: 'exploremate-123.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChblCOQSmp1I-cZpsDKS6K5E_YmDY2-PI',
    appId: '1:792157576621:ios:acb4861ea0a517d63c1524',
    messagingSenderId: '792157576621',
    projectId: 'exploremate-123',
    storageBucket: 'exploremate-123.firebasestorage.app',
    iosBundleId: 'com.example.exploremate',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChblCOQSmp1I-cZpsDKS6K5E_YmDY2-PI',
    appId: '1:792157576621:ios:acb4861ea0a517d63c1524',
    messagingSenderId: '792157576621',
    projectId: 'exploremate-123',
    storageBucket: 'exploremate-123.firebasestorage.app',
    iosBundleId: 'com.example.exploremate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmZztae4oTKf4c8hOifbYKmobenNzBRE4',
    appId: '1:792157576621:web:4c2e9dfcd19321533c1524',
    messagingSenderId: '792157576621',
    projectId: 'exploremate-123',
    authDomain: 'exploremate-123.firebaseapp.com',
    storageBucket: 'exploremate-123.firebasestorage.app',
    measurementId: 'G-CSNL04LDNY',
  );
}
